name: Terraform CI/CD

on:
  push:
    branches:
      - practice
  pull_request:
    branches:
      - practice

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credential
        env:
              AWS_ACCESS_KEY: ${{ secrets.AWS_SANDBOX_ACCESS_KEY }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SANDBOX_SECRET_KEY }}

        run: |
             aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile Sandbox
             aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile Sandbox

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5  # Change to your desired Terraform version

      - name: Terraform Init
        env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SANDBOX_ACCESS_KEY }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SANDBOX_SECRET_KEY }}
        run:  |
              aws sso login --sso_start_url https://patternaccounts.awsapps.com/start/# --sso_region us-east-1 --profile Sandbox 
              terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/practice'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform output -json > output.json
