name: Terraform Workflow

on:
  push:
    branches:
      - practice  # Change to your desired branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SANDBOX_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SANDBOX_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile Sandbox
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile Sandbox
          # Optionally set the default region
          aws configure set region us-east-1 --profile Sandbox

      - name: Export AWS Profile
        run: echo "AWS_PROFILE=Sandbox" >> $GITHUB_ENV   

      - name: Terraform Init
        env:
          AWS_PROFILE: Sandbox  # Use the specified profile
        run: |
          terraform init

      - name: Terraform Plan
        env:
          AWS_PROFILE: Sandbox
        run: |
          terraform plan

      - name: Terraform Apply
        env:
          AWS_PROFILE: Sandbox
        run: |
          terraform apply -auto-approve
